cpuidle: teo: Hardcode `stop_tick`
This is a subsequent patch to 49d8c66 ("cpuidle: Hardcode stop_tick").
This also fixes the following compilation error that is caused by the
the removal of "stop_tick" bool from "select" member at the cpuidle_governor
struct with the above-mentioned patch:

../drivers/cpuidle/governors/teo.c:612:12: error: incompatible function pointer types initializing 'int (*)(struct cpuidle_driver *, struct cpuidle_device *)' with an expression of type 'int (struct cpuidle_driver *, struct cpuidle_device *, bool *)' (aka 'int (struct cpuidle_driver *, struct cpuidle_device *, _Bool *)') [-Werror,-Wincompatible-function-pointer-types]
        .select =       teo_select,
                        ^~~~~~~~~~

Fixes: df72b80bfde ("BACKPORT: cpuidle: New timer events oriented governor for tickless systems")
Signed-off-by: Tashfin Shakeer Rhythm <tashfinshakeerrhythm@gmail.com>